from __future__ import annotations

from typing import Any


DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES = ("en", "ar")
LANGUAGE_LABELS = {
    "en": "English",
    "ar": "العربية",
}
RTL_LANGUAGES = {"ar"}


TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "app.title": "Smart Study Planner",
        "brand.name": "Rafeeqak",
        "hero.kicker": "Smart Study Planner",
        "nav.title": "Navigation",
        "nav.go_to": "Go to",
        "nav.language": "Language",
        "nav.language_picker": "Language",
        "nav.active_course": "Active Course",
        "nav.active_course_label": "Active course",
        "nav.select_course_placeholder": "Create a course to start",
        "nav.new_course": "New course",
        "nav.new_course_placeholder": "New course name",
        "nav.add_course": "Add course",
        "nav.manage_courses": "Manage courses",
        "nav.no_courses": "No courses yet. Add one above to start.",
        "nav.manage_course_label": "Course to manage",
        "nav.rename_course_name": "Course name",
        "nav.save_course": "Save course",
        "nav.course_renamed": "Renamed course to {course_name}.",
        "nav.delete_course": "Delete course",
        "nav.delete_course_caption": "Delete {course_name} and its local plans, quizzes, uploads, and indexed chunks.",
        "nav.delete_course_confirm": "I understand this removes the local course workspace.",
        "nav.course_deleted": "Deleted course: {course_name}.",
        "nav.delete_course_failed": "Could not delete the course files. Reason: {reason}",
        "nav.duplicate_course_name": "A course with that name already exists.",
        "nav.course_missing": "That course is no longer available.",
        "nav.enter_course_name": "Enter a course name first.",
        "nav.active_course_success": "Active course: {course_name}",
        "nav.profile_language_saved": "Language preference saved.",
        "nav.profile_language_local": "Language changed locally. Cloud profile sync is not configured.",
        "nav.profile_language_failed": "Language changed locally. Profile sync failed: {reason}",
        "page.chat.label": "Chat",
        "page.chat.hint": "Ask what to study and get quick coaching.",
        "page.study_plan.label": "Study Plan",
        "page.study_plan.hint": "Create your schedule from exam date and weak topics.",
        "page.upload_materials.label": "Upload Materials",
        "page.upload_materials.hint": "Add your notes and lecture files in one place.",
        "page.quiz.label": "Quiz",
        "page.quiz.hint": "Test yourself and track your performance.",
        "page.progress_dashboard.label": "Progress Dashboard",
        "page.progress_dashboard.hint": "View plans, uploads, and quiz analytics together.",
        "page.account.label": "Account",
        "page.account.hint": "Manage your login session.",
        "page.login.label": "Login",
        "page.login.hint": "Sign in with your Supabase account.",
        "page.signup.label": "Sign up",
        "page.signup.hint": "Create a new account.",
        "course.none_selected": "None selected",
        "common.yes": "Yes",
        "common.no": "No",
        "common.connected": "Connected",
        "common.not_configured": "Not configured",
        "common.delete": "Delete",
        "common.user": "User",
        "common.email": "Email",
        "auth.not_configured": "Authentication is not configured: {reason}",
        "login.title": "Login",
        "login.subtitle": "Sign in to access your saved plans, quiz history, and personalized memory.",
        "login.chip.secure": "Secure access",
        "login.chip.auth": "Supabase Auth",
        "login.accent": "Sign in",
        "login.form_title": "Account login",
        "login.email": "Email",
        "login.email_placeholder": "you@example.com",
        "login.password": "Password",
        "login.submit": "Login",
        "login.required": "Email and password are required.",
        "login.success": "Login successful.",
        "signup.title": "Create Account",
        "signup.subtitle": "Sign up once to save your study memory and continue from any session.",
        "signup.chip.profile": "Personal profile",
        "signup.chip.memory": "Cloud memory",
        "signup.accent": "Sign up",
        "signup.form_title": "New account",
        "signup.full_name": "Full name",
        "signup.full_name_placeholder": "Demo Student",
        "signup.email": "Email",
        "signup.password": "Password",
        "signup.confirm_password": "Confirm password",
        "signup.submit": "Create account",
        "signup.required": "Email and password are required.",
        "signup.password_mismatch": "Passwords do not match.",
        "signup.password_short": "Password must be at least 8 characters.",
        "signup.verify_email": "Account created. Please verify your email, then login.",
        "signup.success": "Account created and logged in.",
        "account.no_session": "No active user session.",
        "account.title": "Account",
        "account.subtitle": "Manage your active session.",
        "account.accent": "Session",
        "account.details": "Session details",
        "account.signed_in_as": "Signed in as: `{email}`",
        "account.logout": "Logout",
        "account.logged_out": "Logged out.",
        "chat.title": "Study Coach Chat",
        "chat.subtitle": "Ask for daily guidance, revision priorities, and next-step recommendations from your planner.",
        "chat.messages_chip": "Messages: {count}",
        "chat.active_plan_chip": "Active plan: {status}",
        "chat.accent": "Conversation mode",
        "chat.empty": "No messages yet. Try: What should I study today?",
        "chat.quick_prompts": "Quick prompts",
        "chat.pick_prompt": "Pick a prompt",
        "chat.prompt.today": "What should I study today?",
        "chat.prompt.weak": "Focus on my weak topics",
        "chat.prompt.checklist": "Give me a quick revision checklist",
        "chat.use_prompt": "Use selected prompt",
        "chat.snapshot": "Session snapshot",
        "chat.total_messages": "Total messages",
        "chat.stored_plans": "Stored plans",
        "chat.latest_summary": "Latest session summary",
        "chat.next_steps": "Suggested next steps",
        "chat.clear": "Clear chat history",
        "chat.input": "Ask your study assistant...",
        "state.course_required": "Create or select a course first so this work stays separated from your other subjects.",
        "planner.title": "Personalized Study Plan",
        "planner.subtitle": "Create an exam-focused schedule with weighted weak-topic coverage and recurring checkpoints.",
        "planner.saved_plans_chip": "Saved plans: {count}",
        "planner.current_day_chip": "Current day: {date}",
        "planner.accent": "Planner",
        "planner.config": "Plan configuration",
        "planner.course_name": "Course name",
        "planner.course_placeholder": "Example: Machine Learning",
        "planner.exam_date": "Exam date",
        "planner.daily_hours": "Available study hours per day",
        "planner.weak_topics": "Weak topics (comma-separated)",
        "planner.weak_placeholder": "Example: SVM, Backpropagation",
        "planner.other_topics": "Other topics (comma-separated)",
        "planner.other_placeholder": "Example: Linear Regression, Decision Trees",
        "planner.generate": "Generate study plan",
        "planner.insights": "Planning insights",
        "planner.tasks_queued": "Tasks queued",
        "planner.weak_tracked": "Weak topics tracked",
        "planner.hours_day": "Hours/day",
        "planner.no_insights": "Generate your first plan to view plan intelligence.",
        "planner.supabase_memory": "Supabase memory",
        "planner.course_required": "Enter a course name so the plan can be saved to a course.",
        "planner.synced": "Study plan synced to Supabase memory.",
        "planner.local_only": "Study plan saved locally only. Reason: {reason}",
        "planner.no_plan": "No active plan yet. Generate one above.",
        "planner.summary": "Created {count} study task(s) for {course_name}. Weak topics are prioritized first: {weak_topics}.",
        "planner.none": "none",
        "planner.timeline": "Current plan timeline",
        "planner.col.study_date": "Study Date",
        "planner.col.topic": "Topic",
        "planner.col.phase": "Phase",
        "planner.col.task": "Task",
        "planner.col.hours": "Hours",
        "planner.col.checkpoint": "Quiz Checkpoint",
        "planner.col.completed": "Completed",
        "planner.timeline_saved": "Plan progress saved.",
        "upload.title": "Course Material Hub",
        "upload.subtitle": "Centralize lecture notes and source files to prepare for retrieval and grounded answers.",
        "upload.files_chip": "Files stored: {count}",
        "upload.chunks_chip": "Indexed chunks: {count}",
        "upload.disk_chip": "Disk usage: {size} MB",
        "upload.accent": "Upload center",
        "upload.add_materials": "Add materials",
        "upload.uploader": "Upload PDFs, slides, or notes",
        "upload.save": "Save uploaded files",
        "upload.select_file": "Select at least one file first.",
        "upload.saved": "Saved {files} file(s) and indexed {chunks} chunk(s).",
        "upload.failed": "{count} file(s) could not be indexed. {details}",
        "upload.rag_ready": "The Course RAG Agent can now retrieve from these materials in Chat.",
        "upload.library": "Library snapshot",
        "upload.stored_files": "Stored files",
        "upload.indexed_chunks": "Indexed chunks",
        "upload.total_size": "Total size",
        "upload.files_heading": "Uploaded files",
        "upload.no_files": "No files uploaded yet.",
        "upload.delete_caption": "Delete removes the source file and its indexed chunks from Course RAG.",
        "upload.col.file_name": "File Name",
        "upload.col.size": "Size (KB)",
        "upload.col.updated": "Updated (UTC)",
        "upload.manage": "Manage files",
        "upload.deleted": "Deleted {file_name} and removed {chunks} indexed chunk(s).",
        "upload.delete_failed": "Could not delete {file_name}. Reason: {reason}",
        "quiz.title": "Assessment Studio",
        "quiz.subtitle": "Generate focused quizzes to validate comprehension and monitor mastery over time.",
        "quiz.attempts_chip": "Attempts: {count}",
        "quiz.avg_chip": "Average score: {score}%",
        "quiz.rag_chip": "RAG chunks: {count}",
        "quiz.accent": "Quiz lab",
        "quiz.setup": "Quiz setup",
        "quiz.topic": "Topic",
        "quiz.topic_required": "Enter a quiz topic first.",
        "quiz.difficulty": "Difficulty",
        "quiz.difficulty.easy": "Easy",
        "quiz.difficulty.medium": "Medium",
        "quiz.difficulty.hard": "Hard",
        "quiz.types": "Question types",
        "quiz.type_required": "Choose at least one question type.",
        "quiz.type.mcq": "MCQ",
        "quiz.type.true_false": "True/False",
        "quiz.type.short_answer": "Short answer",
        "quiz.type.matching": "Matching",
        "quiz.count": "Number of questions",
        "quiz.create": "Create quiz",
        "quiz.performance": "Performance snapshot",
        "quiz.average": "Average",
        "quiz.last_score": "Last score",
        "quiz.no_attempts": "No attempts yet.",
        "quiz.generated": "Quiz generated{source_note}.",
        "quiz.source_note": " using {count} retrieved source chunk(s)",
        "quiz.materials_required": "Upload and index course materials first. Quizzes are generated only from the selected course files.",
        "quiz.material_match_required": "I found uploaded materials, but not enough matching content for that topic. Try a topic name that appears in your files.",
        "quiz.generation_failed": "The quiz could not be generated from the uploaded materials. Try another topic or fewer questions.",
        "quiz.no_quiz": "No active quiz yet. Create one above.",
        "quiz.empty": "The active quiz has no questions. Create a new quiz.",
        "quiz.active": "Active quiz: {topic}",
        "quiz.caption.sources": "Generated from uploaded materials for this course.",
        "quiz.caption.templates": "Generated from uploaded materials for this course.",
        "quiz.answer_title": "Answer questions",
        "quiz.submit": "Submit answers",
        "quiz.synced": "Quiz attempt synced to Supabase memory.",
        "quiz.local_only": "Quiz attempt saved locally only. Reason: {reason}",
        "quiz.feedback": "Question feedback",
        "quiz.correct": "Correct",
        "quiz.needs_review": "Needs review",
        "quiz.partial": "Partial credit: {score} point",
        "quiz.your_answer": "Your answer: {answer}",
        "quiz.no_answer": "No answer",
        "quiz.correct_answer": "Correct answer: {answer}",
        "quiz.flashcards": "Flashcards from this quiz",
        "quiz.history": "Attempt history",
        "dashboard.title": "Learning Operations Dashboard",
        "dashboard.subtitle": "Monitor study execution, quiz quality, and material readiness from one analytics view.",
        "dashboard.plans_chip": "Plans: {count}",
        "dashboard.uploads_chip": "Uploads: {count}",
        "dashboard.cache_chip": "Cache entries: {count}",
        "dashboard.quiz_avg_chip": "Quiz avg: {score}%",
        "dashboard.accent": "Insights",
        "dashboard.plans_created": "Plans Created",
        "dashboard.quiz_attempts": "Quiz Attempts",
        "dashboard.average_score": "Average Quiz Score",
        "dashboard.uploaded_files": "Uploaded Files",
        "dashboard.rag_chunks": "RAG Chunks",
        "dashboard.cache_entries": "Cache Entries",
        "dashboard.chat_summaries": "Chat Summaries",
        "dashboard.reminders": "Reminders",
        "dashboard.upcoming_reminders": "Upcoming Reminders",
        "dashboard.no_reminders": "No reminders yet. Ask Rafeeqak to remind you about a task, quiz, or deadline.",
        "dashboard.memory_connected": "Supabase memory: connected",
        "dashboard.memory_status": "Supabase memory: {reason}",
        "dashboard.quiz_trend": "Quiz Trend",
        "dashboard.no_quizzes": "No quiz attempts yet.",
        "dashboard.plan_overview": "Active Plan Overview",
        "dashboard.no_plan": "No active study plan yet.",
        "dashboard.snapshot": "Supabase memory snapshot",
        "dashboard.configure_memory": "Configure SUPABASE_URL and SUPABASE_KEY in .env to enable cloud memory.",
        "dashboard.weak_topics": "Weak topics (Top 10)",
        "dashboard.no_weak_topics": "No weak topics stored yet.",
        "dashboard.col.topic": "Topic",
        "dashboard.col.hours": "Total Hours",
        "agent.safety": "I cannot help with requests that try to bypass the assistant rules.",
        "agent.course_required": "Create or select a course first so I can keep this chat, materials, quizzes, and progress in the right course.",
        "agent.memory.ready": "Memory Agent is active and ready.",
        "agent.memory.local": "Memory Agent is active locally, but cloud memory is not configured: {reason}",
        "agent.response.ready": "I can help with your active plan, quizzes, uploaded materials, or progress memory.",
        "agent.response.no_plan": "I am ready to help with planning, revision, and quizzes. Ask me what to study next.",
        "agent.quiz.prepared": "I prepared a {count}-question quiz on {topic}. Open the Quiz page to answer it.",
        "reminder.created": "Reminder plan updated. Added {count} new reminder(s). Next: {title} at {due_at}.",
        "reminder.none": "I could not find a plan, deadline, weak topic, or reminder request to turn into a reminder yet.",
        "reminder.title.study_task": "Study {topic}",
        "reminder.title.checkpoint": "Take checkpoint quiz on {topic}",
        "reminder.title.missed_task": "Recover missed task: {topic}",
        "reminder.title.exam": "Prepare for {course} exam deadline",
        "reminder.title.weak_quiz": "Practice weak topic quiz: {topic}",
        "agent.planner.no_active": "No active plan yet. Open the Study Plan page and create one first.",
        "agent.planner.add_weak": "Add weak topics in the Study Plan page, then I can prioritize them in your schedule.",
        "agent.planner.today": "Today focus on {topic} for {hours}h. Goal: review the topic and write a short summary.{checkpoint_note}",
        "agent.planner.checkpoint": " It also includes a short quiz.",
        "agent.planner.priorities": "Your current plan gives weak topics extra review time before regular topics. Priority topics: {topics}.",
        "agent.planner.no_weak": "Your current plan has no marked weak topics, so revision is spread evenly across topics.",
        "rag.no_materials": "Upload course materials first, then I can answer with sources from your notes.",
        "rag.no_match": "I found indexed materials, but not a strong match for that question. Try naming the topic exactly as it appears in your notes.",
        "rag.clarify": "What topic would you like me to explain?\nFor example:\n\n- Explain SOC tiers\n- Explain threat hunting\n- Explain the role of a SOC analyst",
        "rag.answer_intro": "Based on your uploaded materials for {course_name}, here is the relevant answer to: {question}",
        "rag.sources": "Sources: {sources}",
        "evaluator.empty": "No quiz questions were provided.",
        "evaluator.summary": "Score: {correct}/{total} ({score_percent}%).",
        "evaluator.excellent": "Great mastery of {topic}. Move to mixed practice and raise the difficulty next time.",
        "evaluator.good": "Good progress. Review missed and partial-credit explanations, then retry the weakest question type.",
        "evaluator.review": "Review {topic} again, then retry a short quiz focused on the question types you missed.",
        "db.no_deadline": "No exam deadline is saved yet. Create a study plan first.",
        "db.deadline": "The exam deadline for {course} is {exam_date}. {days_text}",
        "db.no_progress": "There is no active plan to measure progress. Create a study plan first.",
        "db.progress": "You completed {completed} of {total} tasks ({percent}%).",
        "db.next_task": " Next task: {topic} on {date} for {hours}h.",
        "db.no_scores": "No quiz attempts are recorded yet.",
        "db.scores": "You have {attempts} quiz attempt(s). Average score is {average}%. Latest score was {score}% on {topic}.",
        "db.no_weak": "No weak topics are saved yet.",
        "db.weak": "Current weak topics: {topics}. Prioritize them in revision and short quizzes.",
        "db.no_courses": "No courses are saved yet.",
        "db.all_scores": "All-course quiz summary: {rows}",
        "db.all_weak": "All-course weak-topic summary: {rows}",
        "db.all_deadlines": "All-course deadline summary: {rows}",
        "db.all_progress": "All-course progress summary: {rows}",
        "db.no_weak_short": "no weak topics",
        "db.no_deadline_short": "no deadline",
        "db.days_remaining": "{days} day(s) remaining.",
        "db.exam_today": "The exam is today.",
        "db.exam_past": "It was {days} day(s) ago.",
    },
    "ar": {
        "app.title": "رفيقك للمذاكرة",
        "brand.name": "رفيقك",
        "hero.kicker": "مخطط مذاكرة ذكي",
        "nav.title": "التنقل",
        "nav.go_to": "انتقل إلى",
        "nav.language": "اللغة",
        "nav.language_picker": "اللغة",
        "nav.active_course": "المقرر النشط",
        "nav.active_course_label": "المقرر النشط",
        "nav.select_course_placeholder": "أنشئ مقررا لتبدأ",
        "nav.new_course": "مقرر جديد",
        "nav.new_course_placeholder": "اسم المقرر الجديد",
        "nav.add_course": "إضافة مقرر",
        "nav.manage_courses": "إدارة المقررات",
        "nav.no_courses": "لا توجد مقررات بعد. أضف مقررا بالأعلى لتبدأ.",
        "nav.manage_course_label": "المقرر المراد إدارته",
        "nav.rename_course_name": "اسم المقرر",
        "nav.save_course": "حفظ المقرر",
        "nav.course_renamed": "تمت إعادة تسمية المقرر إلى {course_name}.",
        "nav.delete_course": "حذف المقرر",
        "nav.delete_course_caption": "حذف {course_name} وخططه واختباراته وملفاته والفهارس المحلية.",
        "nav.delete_course_confirm": "أفهم أن هذا سيزيل مساحة عمل المقرر محليا.",
        "nav.course_deleted": "تم حذف المقرر: {course_name}.",
        "nav.delete_course_failed": "تعذر حذف ملفات المقرر. السبب: {reason}",
        "nav.duplicate_course_name": "يوجد مقرر بهذا الاسم بالفعل.",
        "nav.course_missing": "هذا المقرر لم يعد متاحا.",
        "nav.enter_course_name": "اكتب اسم المقرر أولا.",
        "nav.active_course_success": "المقرر النشط: {course_name}",
        "nav.profile_language_saved": "تم حفظ تفضيل اللغة.",
        "nav.profile_language_local": "تم تغيير اللغة محليا. مزامنة الملف السحابي غير مفعلة.",
        "nav.profile_language_failed": "تم تغيير اللغة محليا. فشلت مزامنة الملف: {reason}",
        "page.chat.label": "المحادثة",
        "page.chat.hint": "اسأل ماذا تذاكر واحصل على توجيه سريع.",
        "page.study_plan.label": "خطة المذاكرة",
        "page.study_plan.hint": "أنشئ جدولك من موعد الامتحان ونقاط الضعف.",
        "page.upload_materials.label": "رفع المواد",
        "page.upload_materials.hint": "اجمع ملاحظاتك وملفات المحاضرات في مكان واحد.",
        "page.quiz.label": "اختبار",
        "page.quiz.hint": "اختبر نفسك وتابع أداءك.",
        "page.progress_dashboard.label": "لوحة التقدم",
        "page.progress_dashboard.hint": "اعرض الخطط والملفات وتحليلات الاختبارات معا.",
        "page.account.label": "الحساب",
        "page.account.hint": "إدارة جلسة الدخول.",
        "page.login.label": "تسجيل الدخول",
        "page.login.hint": "سجل الدخول بحساب Supabase.",
        "page.signup.label": "إنشاء حساب",
        "page.signup.hint": "أنشئ حسابا جديدا.",
        "course.none_selected": "لا يوجد مقرر محدد",
        "common.yes": "نعم",
        "common.no": "لا",
        "common.connected": "متصل",
        "common.not_configured": "غير مفعل",
        "common.delete": "حذف",
        "common.user": "المستخدم",
        "common.email": "البريد",
        "auth.not_configured": "المصادقة غير مفعلة: {reason}",
        "login.title": "تسجيل الدخول",
        "login.subtitle": "ادخل إلى خططك المحفوظة وسجل الاختبارات والذاكرة الشخصية.",
        "login.chip.secure": "دخول آمن",
        "login.chip.auth": "مصادقة Supabase",
        "login.accent": "دخول",
        "login.form_title": "تسجيل الدخول للحساب",
        "login.email": "البريد الإلكتروني",
        "login.email_placeholder": "you@example.com",
        "login.password": "كلمة المرور",
        "login.submit": "تسجيل الدخول",
        "login.required": "البريد الإلكتروني وكلمة المرور مطلوبان.",
        "login.success": "تم تسجيل الدخول بنجاح.",
        "signup.title": "إنشاء حساب",
        "signup.subtitle": "أنشئ حسابا مرة واحدة لحفظ ذاكرة المذاكرة والمتابعة من أي جلسة.",
        "signup.chip.profile": "ملف شخصي",
        "signup.chip.memory": "ذاكرة سحابية",
        "signup.accent": "تسجيل",
        "signup.form_title": "حساب جديد",
        "signup.full_name": "الاسم الكامل",
        "signup.full_name_placeholder": "طالب تجريبي",
        "signup.email": "البريد الإلكتروني",
        "signup.password": "كلمة المرور",
        "signup.confirm_password": "تأكيد كلمة المرور",
        "signup.submit": "إنشاء حساب",
        "signup.required": "البريد الإلكتروني وكلمة المرور مطلوبان.",
        "signup.password_mismatch": "كلمتا المرور غير متطابقتين.",
        "signup.password_short": "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
        "signup.verify_email": "تم إنشاء الحساب. تحقق من بريدك ثم سجل الدخول.",
        "signup.success": "تم إنشاء الحساب وتسجيل الدخول.",
        "account.no_session": "لا توجد جلسة مستخدم نشطة.",
        "account.title": "الحساب",
        "account.subtitle": "إدارة جلسة الدخول الحالية.",
        "account.accent": "الجلسة",
        "account.details": "تفاصيل الجلسة",
        "account.signed_in_as": "مسجل الدخول باسم: `{email}`",
        "account.logout": "تسجيل الخروج",
        "account.logged_out": "تم تسجيل الخروج.",
        "chat.title": "محادثة مدرب المذاكرة",
        "chat.subtitle": "اسأل عن إرشاد اليوم وأولويات المراجعة والخطوة التالية من خطتك.",
        "chat.messages_chip": "الرسائل: {count}",
        "chat.active_plan_chip": "خطة نشطة: {status}",
        "chat.accent": "وضع المحادثة",
        "chat.empty": "لا توجد رسائل بعد. جرب: ماذا أذاكر اليوم؟",
        "chat.quick_prompts": "أسئلة سريعة",
        "chat.pick_prompt": "اختر سؤالا",
        "chat.prompt.today": "ماذا أذاكر اليوم؟",
        "chat.prompt.weak": "ركز على نقاط ضعفي",
        "chat.prompt.checklist": "اعطني قائمة مراجعة سريعة",
        "chat.use_prompt": "استخدم السؤال المحدد",
        "chat.snapshot": "ملخص الجلسة",
        "chat.total_messages": "إجمالي الرسائل",
        "chat.stored_plans": "الخطط المحفوظة",
        "chat.latest_summary": "آخر ملخص للجلسة",
        "chat.next_steps": "الخطوات التالية المقترحة",
        "chat.clear": "مسح المحادثة",
        "chat.input": "اسأل مساعد المذاكرة...",
        "state.course_required": "أنشئ أو اختر مقررا أولا حتى تبقى البيانات منفصلة عن باقي المواد.",
        "planner.title": "خطة مذاكرة شخصية",
        "planner.subtitle": "أنشئ جدولا موجها للامتحان مع أولوية لنقاط الضعف ونقاط تحقق متكررة.",
        "planner.saved_plans_chip": "الخطط المحفوظة: {count}",
        "planner.current_day_chip": "اليوم الحالي: {date}",
        "planner.accent": "المخطط",
        "planner.config": "إعدادات الخطة",
        "planner.course_name": "اسم المقرر",
        "planner.course_placeholder": "مثال: تعلم الآلة",
        "planner.exam_date": "موعد الامتحان",
        "planner.daily_hours": "ساعات المذاكرة المتاحة يوميا",
        "planner.weak_topics": "نقاط الضعف (مفصولة بفواصل)",
        "planner.weak_placeholder": "مثال: SVM, Backpropagation",
        "planner.other_topics": "موضوعات أخرى (مفصولة بفواصل)",
        "planner.other_placeholder": "مثال: Linear Regression, Decision Trees",
        "planner.generate": "إنشاء خطة مذاكرة",
        "planner.insights": "مؤشرات التخطيط",
        "planner.tasks_queued": "المهام المجدولة",
        "planner.weak_tracked": "نقاط الضعف المتابعة",
        "planner.hours_day": "ساعات/اليوم",
        "planner.no_insights": "أنشئ أول خطة لعرض مؤشرات التخطيط.",
        "planner.supabase_memory": "ذاكرة Supabase",
        "planner.course_required": "اكتب اسم المقرر حتى تحفظ الخطة داخله.",
        "planner.synced": "تمت مزامنة خطة المذاكرة مع ذاكرة Supabase.",
        "planner.local_only": "تم حفظ خطة المذاكرة محليا فقط. السبب: {reason}",
        "planner.no_plan": "لا توجد خطة نشطة بعد. أنشئ واحدة بالأعلى.",
        "planner.summary": "تم إنشاء {count} مهمة مذاكرة لمقرر {course_name}. نقاط الضعف لها الأولوية أولا: {weak_topics}.",
        "planner.none": "لا توجد",
        "planner.timeline": "الجدول الحالي للخطة",
        "planner.col.study_date": "تاريخ المذاكرة",
        "planner.col.topic": "الموضوع",
        "planner.col.phase": "المرحلة",
        "planner.col.task": "المهمة",
        "planner.col.hours": "الساعات",
        "planner.col.checkpoint": "اختبار تحقق",
        "planner.col.completed": "مكتمل",
        "planner.timeline_saved": "تم حفظ تقدم الخطة.",
        "upload.title": "مركز مواد المقرر",
        "upload.subtitle": "اجمع المحاضرات والملاحظات والملفات حتى تصبح جاهزة للاسترجاع والإجابات الموثقة.",
        "upload.files_chip": "الملفات المحفوظة: {count}",
        "upload.chunks_chip": "الأجزاء المفهرسة: {count}",
        "upload.disk_chip": "استخدام القرص: {size} MB",
        "upload.accent": "مركز الرفع",
        "upload.add_materials": "إضافة مواد",
        "upload.uploader": "ارفع ملفات PDF أو شرائح أو ملاحظات",
        "upload.save": "حفظ الملفات المرفوعة",
        "upload.select_file": "اختر ملفا واحدا على الأقل أولا.",
        "upload.saved": "تم حفظ {files} ملف وفهرسة {chunks} جزء.",
        "upload.failed": "تعذر فهرسة {count} ملف. {details}",
        "upload.rag_ready": "يمكن لوكيل RAG الآن الاسترجاع من هذه المواد داخل المحادثة.",
        "upload.library": "ملخص المكتبة",
        "upload.stored_files": "الملفات المحفوظة",
        "upload.indexed_chunks": "الأجزاء المفهرسة",
        "upload.total_size": "الحجم الكلي",
        "upload.files_heading": "الملفات المرفوعة",
        "upload.no_files": "لا توجد ملفات مرفوعة بعد.",
        "upload.delete_caption": "الحذف يزيل الملف الأصلي وأجزاءه المفهرسة من RAG.",
        "upload.col.file_name": "اسم الملف",
        "upload.col.size": "الحجم (KB)",
        "upload.col.updated": "آخر تحديث (UTC)",
        "upload.manage": "إدارة الملفات",
        "upload.deleted": "تم حذف {file_name} وإزالة {chunks} جزء مفهرس.",
        "upload.delete_failed": "تعذر حذف {file_name}. السبب: {reason}",
        "quiz.title": "استوديو التقييم",
        "quiz.subtitle": "أنشئ اختبارات مركزة للتحقق من الفهم ومتابعة الإتقان بمرور الوقت.",
        "quiz.attempts_chip": "المحاولات: {count}",
        "quiz.avg_chip": "متوسط الدرجة: {score}%",
        "quiz.rag_chip": "أجزاء RAG: {count}",
        "quiz.accent": "معمل الاختبار",
        "quiz.setup": "إعداد الاختبار",
        "quiz.topic": "الموضوع",
        "quiz.topic_required": "اكتب موضوع الاختبار أولا.",
        "quiz.difficulty": "الصعوبة",
        "quiz.difficulty.easy": "سهل",
        "quiz.difficulty.medium": "متوسط",
        "quiz.difficulty.hard": "صعب",
        "quiz.types": "أنواع الأسئلة",
        "quiz.type_required": "اختر نوع سؤال واحدا على الأقل.",
        "quiz.type.mcq": "اختيار من متعدد",
        "quiz.type.true_false": "صح/خطأ",
        "quiz.type.short_answer": "إجابة قصيرة",
        "quiz.type.matching": "مطابقة",
        "quiz.count": "عدد الأسئلة",
        "quiz.create": "إنشاء اختبار",
        "quiz.performance": "ملخص الأداء",
        "quiz.average": "المتوسط",
        "quiz.last_score": "آخر درجة",
        "quiz.no_attempts": "لا توجد محاولات بعد.",
        "quiz.generated": "تم إنشاء الاختبار{source_note}.",
        "quiz.source_note": " باستخدام {count} جزء مسترجع من المصادر",
        "quiz.materials_required": "ارفع مواد المقرر وافهرسها أولا. يتم إنشاء الاختبارات من ملفات المقرر المحدد فقط.",
        "quiz.material_match_required": "وجدت مواد مرفوعة، لكن لا توجد أجزاء كافية مطابقة لهذا الموضوع. جرب اسم موضوع موجود في ملفاتك.",
        "quiz.generation_failed": "تعذر إنشاء الاختبار من المواد المرفوعة. جرب موضوعا آخر أو عددا أقل من الأسئلة.",
        "quiz.no_quiz": "لا يوجد اختبار نشط بعد. أنشئ واحدا بالأعلى.",
        "quiz.empty": "الاختبار النشط لا يحتوي على أسئلة. أنشئ اختبارا جديدا.",
        "quiz.active": "الاختبار النشط: {topic}",
        "quiz.caption.sources": "تم إنشاؤه من مواد هذا المقرر المرفوعة.",
        "quiz.caption.templates": "تم إنشاؤه من مواد هذا المقرر المرفوعة.",
        "quiz.answer_title": "أجب عن الأسئلة",
        "quiz.submit": "إرسال الإجابات",
        "quiz.synced": "تمت مزامنة محاولة الاختبار مع ذاكرة Supabase.",
        "quiz.local_only": "تم حفظ محاولة الاختبار محليا فقط. السبب: {reason}",
        "quiz.feedback": "تغذية راجعة للأسئلة",
        "quiz.correct": "صحيح",
        "quiz.needs_review": "يحتاج مراجعة",
        "quiz.partial": "درجة جزئية: {score} نقطة",
        "quiz.your_answer": "إجابتك: {answer}",
        "quiz.no_answer": "لا توجد إجابة",
        "quiz.correct_answer": "الإجابة الصحيحة: {answer}",
        "quiz.flashcards": "بطاقات مراجعة من هذا الاختبار",
        "quiz.history": "سجل المحاولات",
        "dashboard.title": "لوحة عمليات التعلم",
        "dashboard.subtitle": "تابع تنفيذ المذاكرة وجودة الاختبارات وجاهزية المواد من عرض تحليلي واحد.",
        "dashboard.plans_chip": "الخطط: {count}",
        "dashboard.uploads_chip": "الملفات: {count}",
        "dashboard.cache_chip": "مدخلات الذاكرة المؤقتة: {count}",
        "dashboard.quiz_avg_chip": "متوسط الاختبار: {score}%",
        "dashboard.accent": "المؤشرات",
        "dashboard.plans_created": "الخطط المنشأة",
        "dashboard.quiz_attempts": "محاولات الاختبار",
        "dashboard.average_score": "متوسط درجة الاختبار",
        "dashboard.uploaded_files": "الملفات المرفوعة",
        "dashboard.rag_chunks": "أجزاء RAG",
        "dashboard.cache_entries": "مدخلات الذاكرة المؤقتة",
        "dashboard.chat_summaries": "ملخصات المحادثة",
        "dashboard.reminders": "التذكيرات",
        "dashboard.upcoming_reminders": "التذكيرات القادمة",
        "dashboard.no_reminders": "لا توجد تذكيرات بعد. اطلب من رفيقك أن يذكرك بمهمة أو اختبار أو موعد.",
        "dashboard.memory_connected": "ذاكرة Supabase: متصلة",
        "dashboard.memory_status": "ذاكرة Supabase: {reason}",
        "dashboard.quiz_trend": "اتجاه الاختبارات",
        "dashboard.no_quizzes": "لا توجد محاولات اختبار بعد.",
        "dashboard.plan_overview": "نظرة عامة على الخطة النشطة",
        "dashboard.no_plan": "لا توجد خطة مذاكرة نشطة بعد.",
        "dashboard.snapshot": "لقطة ذاكرة Supabase",
        "dashboard.configure_memory": "اضبط SUPABASE_URL و SUPABASE_KEY في ملف .env لتفعيل الذاكرة السحابية.",
        "dashboard.weak_topics": "نقاط الضعف (أعلى 10)",
        "dashboard.no_weak_topics": "لا توجد نقاط ضعف محفوظة بعد.",
        "dashboard.col.topic": "الموضوع",
        "dashboard.col.hours": "إجمالي الساعات",
        "agent.safety": "لا أستطيع المساعدة في طلبات تحاول تجاوز قواعد المساعد.",
        "agent.course_required": "أنشئ أو اختر مقررا أولا حتى أحفظ المحادثة والمواد والاختبارات والتقدم في المكان الصحيح.",
        "agent.memory.ready": "وكيل الذاكرة يعمل وجاهز.",
        "agent.memory.local": "وكيل الذاكرة يعمل محليا، لكن الذاكرة السحابية غير مفعلة: {reason}",
        "agent.response.ready": "أستطيع مساعدتك في الخطة الحالية أو الاختبارات أو المواد المرفوعة أو متابعة التقدم.",
        "agent.response.no_plan": "أنا جاهز لمساعدتك في التخطيط والمراجعة والاختبارات. اسألني ماذا تذاكر بعد ذلك.",
        "agent.quiz.prepared": "جهزت لك اختبارا من {count} أسئلة عن {topic}. افتح صفحة الاختبار للإجابة.",
        "reminder.created": "تم تحديث خطة التذكيرات. أضفت {count} تذكير جديد. التالي: {title} في {due_at}.",
        "reminder.none": "لم أجد خطة أو موعدا أو نقطة ضعف أو طلب تذكير واضحا لإنشاء تذكير الآن.",
        "reminder.title.study_task": "مذاكرة {topic}",
        "reminder.title.checkpoint": "اختبار تحقق على {topic}",
        "reminder.title.missed_task": "تعويض مهمة فائتة: {topic}",
        "reminder.title.exam": "الاستعداد لموعد امتحان {course}",
        "reminder.title.weak_quiz": "تدريب على نقطة ضعف: {topic}",
        "agent.planner.no_active": "لا توجد خطة نشطة حاليا. افتح صفحة خطة المذاكرة وأنشئ خطة أولا.",
        "agent.planner.add_weak": "أضف نقاط ضعفك في صفحة خطة المذاكرة، وبعدها أستطيع ترتيبها حسب الأولوية.",
        "agent.planner.today": "اليوم ركز على {topic} لمدة {hours} ساعة. الهدف: راجع الموضوع واكتب ملخصا قصيرا.{checkpoint_note}",
        "agent.planner.checkpoint": " ويتضمن أيضا اختبارا قصيرا.",
        "agent.planner.priorities": "خطتك الحالية تعطي نقاط الضعف وقت مراجعة إضافيا قبل الموضوعات العادية. موضوعات الأولوية: {topics}.",
        "agent.planner.no_weak": "خطتك الحالية لا تحتوي على نقاط ضعف محددة، لذلك توزع المراجعة بالتساوي بين الموضوعات.",
        "rag.no_materials": "ارفع مواد المقرر أولا، وبعدها أستطيع إجابتك بمصادر من ملاحظاتك.",
        "rag.no_match": "وجدت مواد مفهرسة، لكن لم أجد جزءا مناسبا لهذا السؤال. حاول كتابة اسم الموضوع كما يظهر في ملاحظاتك.",
        "rag.clarify": "\u0645\u0645\u0643\u0646 \u062a\u062d\u062f\u062f \u0627\u0644\u0645\u0648\u0636\u0648\u0639 \u0627\u0644\u0644\u064a \u062a\u062d\u0628 \u0623\u0634\u0631\u062d\u0647\u061f\n\u0645\u062b\u0627\u0644:\n\n- \u0627\u0634\u0631\u062d SOC tiers\n- \u0627\u0634\u0631\u062d threat hunting\n- \u0627\u0634\u0631\u062d \u062f\u0648\u0631 SOC analyst",
        "rag.answer_intro": "بناء على المواد التي رفعتها لمقرر {course_name}، هذه أهم النقاط المرتبطة بسؤالك: {question}",
        "rag.sources": "المصادر: {sources}",
        "evaluator.empty": "لم يتم توفير أسئلة للاختبار.",
        "evaluator.summary": "درجتك: {correct}/{total} ({score_percent}%).",
        "evaluator.excellent": "ممتاز في {topic}. انتقل إلى تدريب مختلط وارفع الصعوبة في المرة القادمة.",
        "evaluator.good": "تقدم جيد. راجع شرح الأخطاء والأسئلة ذات الدرجة الجزئية ثم أعد أضعف نوع سؤال.",
        "evaluator.review": "راجع {topic} مرة أخرى، ثم أعد اختبارا قصيرا يركز على أنواع الأسئلة التي أخطأت فيها.",
        "db.no_deadline": "لا يوجد موعد امتحان محفوظ بعد. أنشئ خطة مذاكرة أولا.",
        "db.deadline": "موعد امتحان {course} هو {exam_date}. {days_text}",
        "db.no_progress": "لا توجد خطة نشطة لقياس التقدم. أنشئ خطة مذاكرة أولا.",
        "db.progress": "أنجزت {completed} من {total} مهمة ({percent}%).",
        "db.next_task": " المهمة التالية: {topic} يوم {date} لمدة {hours} ساعة.",
        "db.no_scores": "لا توجد محاولات اختبار مسجلة بعد.",
        "db.scores": "لديك {attempts} محاولة اختبار. متوسط الدرجة {average}%. آخر درجة كانت {score}% في {topic}.",
        "db.no_weak": "لا توجد نقاط ضعف محفوظة بعد.",
        "db.weak": "نقاط الضعف الحالية: {topics}. أعطها أولوية في المراجعة والاختبارات القصيرة.",
        "db.no_courses": "لا توجد مقررات محفوظة بعد.",
        "db.all_scores": "ملخص اختبارات كل المقررات: {rows}",
        "db.all_weak": "ملخص نقاط الضعف لكل المقررات: {rows}",
        "db.all_deadlines": "ملخص مواعيد كل المقررات: {rows}",
        "db.all_progress": "ملخص تقدم كل المقررات: {rows}",
        "db.no_weak_short": "لا توجد نقاط ضعف",
        "db.no_deadline_short": "لا يوجد موعد",
        "db.days_remaining": "متبق {days} يوم.",
        "db.exam_today": "الامتحان اليوم.",
        "db.exam_past": "كان منذ {days} يوم.",
    },
}


def normalize_language(language: str | None) -> str:
    if not language:
        return DEFAULT_LANGUAGE
    normalized = str(language).strip().lower()
    if normalized.startswith("ar"):
        return "ar"
    if normalized.startswith("en"):
        return "en"
    return DEFAULT_LANGUAGE


def is_rtl(language: str | None) -> bool:
    return normalize_language(language) in RTL_LANGUAGES


def detect_language(text: str) -> str:
    return "ar" if any("\u0600" <= char <= "\u06FF" for char in str(text)) else "en"


def language_label(language: str | None) -> str:
    return LANGUAGE_LABELS[normalize_language(language)]


def t(key: str, language: str | None = DEFAULT_LANGUAGE, **values: Any) -> str:
    lang = normalize_language(language)
    template = TRANSLATIONS.get(lang, {}).get(key)
    if template is None:
        template = TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key)
    if not values:
        return template
    try:
        return template.format(**values)
    except (KeyError, ValueError):
        return template
